import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MyHeader from "@/components/header";
import Notification from "@/components/notificaton"; // import Notification component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // all page contents
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} 
      >
        {/* Mount the notification component once globally */}
        <Notification />

        <MyHeader />  
        {children}
        <h1 className="text-center text-red-600">@All Right Reserved</h1>
      </body>
    </html>
  );
}
